In [1]:
import pandas as pd

In [2]:
#pd.DataFrame():Creates a DataFrame from a dictionary, list, or array.
import pandas as pd

df = pd.DataFrame({"SET1":['20','30'],"SET2":['56','80']
})

print(df)

  SET1 SET2
0   20   56
1   30   80

In [3]:
#df.head(): Returns the first 5 rows (or the specified number of rows).

df.head()

  SET1 SET2
0   20   56
1   30   80

In [4]:
#pd.Series(): Creates a one-dimensional array-like object.
d = pd.Series([3,6,9,12,15])
print(d)

0     3
1     6
2     9
3    12
4    15
dtype: int64

In [5]:
#df.tail(): return the last ending rows of the DataFrame. By default, it returns the last 5 rows.
df.tail()

  SET1 SET2
0   20   56
1   30   80

In [6]:
#df.info:Displays DataFrame information such as number of rows, columns, data types, and memory usage.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SET1    2 non-null      object
 1   SET2    2 non-null      object
dtypes: object(2)
memory usage: 160.0+ bytes

In [7]:
#df.shape:returns the number of rows and columns in the DataFrame as a tuple (rows, columns).
print(df.shape)

(2, 2)

In [8]:
#describe():Displays statistical summary of numeric columns.
df.describe()

       SET1 SET2
count     2    2
unique    2    2
top      20   56
freq      1    1

In [9]:
#df.info():Displays DataFrame information such as number of rows, columns, data types, and memory usage.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SET1    2 non-null      object
 1   SET2    2 non-null      object
dtypes: object(2)
memory usage: 160.0+ bytes

In [10]:
#df.columns:Returns the column labels of the DataFrame as an Index object.
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.columns)

Index(['A', 'B'], dtype='object')

In [11]:
#df.index:Returns row indexes.
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [12]:
#df.dtypes: It shows the data type of each column like integer, float, string, etc.
print(df.dtypes)

A    int64
B    int64
dtype: object

In [13]:
#df.loc[]:It selects rows and columns using labels.
print(df.loc[0])

A    1
B    4
Name: 0, dtype: int64

In [14]:
#df.iloc[]:It selects rows and columns using integer positions.
print(df.iloc[0])

A    1
B    4
Name: 0, dtype: int64

In [15]:
#df.fillna():It is used to handle missing values instead of deleting rows.
print(df.fillna(0))

   A  B
0  1  4
1  2  5
2  3  6

In [16]:
#df.dropna():It removes rows where values are missing.
df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Marks': [80, None, 70]
})

print(df.dropna())

  Name  Marks
0    A   80.0
2    C   70.0

In [17]:
#df.isnull():True means the value is missing; False means it is present.
print(df.isnull())

    Name  Marks
0  False  False
1  False   True
2  False  False

In [18]:
#df.fillna():It is used to handle missing values instead of deleting rows.
print(df.fillna(0))

  Name  Marks
0    A   80.0
1    B    0.0
2    C   70.0

In [19]:
#df.sort_values(): Sorts rows by column values.
print(df.sort_values('Marks'))

  Name  Marks
2    C   70.0
0    A   80.0
1    B    NaN

In [20]:
#df.sort_index():Sorts by index.
df.sort_index()

  Name  Marks
0    A   80.0
1    B    NaN
2    C   70.0

In [21]:
#df.drop():removes rows or columns based on labels.
df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Marks': [80, 90, 70]
})
print(df.drop('Marks', axis=1))

  Name
0    A
1    B
2    C

In [22]:
#df.replace():Replaces values in the DataFrame with specified values.
df = pd.DataFrame({
    'Name': ['A', 'B', 'C'],
    'Marks': [80, 90, 70]
})
print(df.replace(80, 85))

  Name  Marks
0    A     85
1    B     90
2    C     70

In [23]:
#df.groupby():groups the DataFrame by one or more columns and allows for aggregation operations.
df = pd.DataFrame({
    'Name': ['R', 'P', 'A', 'S'],
    'Marks': [80, 90, 70, 85]
})
grouped = df.groupby('Name')
print(grouped.mean())

      Marks
Name
A      70.0
P      90.0
R      80.0
S      85.0

In [24]:
#df.rename():Renames columns or indexes in the DataFrame.
df = pd.DataFrame({
    'Name': ['ANU', 'SAI', 'CHINNA'],
    'Marks': [70, 88, 99]
})
df_renamed = df.rename(columns={'Name': 'Student Name', 'Marks': 'Score'})
print(df_renamed)

  Student Name  Score
0          ANU     70
1          SAI     88
2       CHINNA     99

In [25]:
#df.mean():Calculates the mean of numeric columns in the DataFrame.
df = pd.DataFrame({
    'Name': ['ANU', 'SAI', 'CHINNA'],
    'Marks': [70, 88, 99]
})
mean_marks = df['Marks'].mean()
print("Mean of Marks:", mean_marks)

Mean of Marks: 85.66666666666667

In [26]:
#df.median():Calculates the median of dataframe columns.
print(df['Marks'].median())

88.0

In [27]:
#df.mode():It finds the most repeated value.
print(df['Marks'].mode())

0    70
1    88
2    99
Name: Marks, dtype: int64

In [28]:
#df.sum():It calculates the total of numerical values.
df = pd.DataFrame({
    'total points': [80, 90, 70]
})

print(df['total points'].sum())

240

In [29]:
#df.max(): It returns the largest value.
print(df['total points'].max())

90

In [30]:
#df.min(): It returns the smallest value.
print(df['total points'].min())

70

In [31]:
#df.count(): It counts non-missing values in each column.
print(df['total points'].count())

3

In [32]:
#df.var():It calculates the variance of numerical data.
print(df['total points'].var())

100.0

In [33]:
#df.std(): It calculates the standard deviation of numerical data.
print(df['total points'].std())

10.0

In [34]:
#df.apply():It applies a function to each value, row, or column.
import pandas as pd

df = pd.DataFrame({
    'total points': [56, 67, 87]
})

df['total points'] = df['total points'].apply(lambda x: x + 5)

print(df)

   total points
0            61
1            72
2            92

In [35]:
#df.corr():It calculates the correlation between numerical columns.
df = pd.DataFrame({
    'student': [1, 2, 3, 4],
    'total points': [56, 67, 87, 98]
})

print(df.corr())

               student  total points
student       1.000000      0.992486
total points  0.992486      1.000000

In [36]:
#df.map():It applies a function to every value in a Series.
df = pd.DataFrame({
    'total points': [56, 67, 87]
})

print(df['total points'].map(lambda x: x * 2))

0    112
1    134
2    174
Name: total points, dtype: int64

In [37]:
#df.sort_values():It sorts rows based on one or more columns.
df = pd.DataFrame({
    'Name': ['Anu', 'Sai', 'chinna'],
    'total points': [80, 95, 70]
})

print(df.sort_values('total points', ascending=False))

     Name  total points
1     Sai            95
0     Anu            80
2  chinna            70

In [38]:
#pd.read_csv():It is used to load CSV data into Pandas.
try:
    df = pd.read_csv('data.csv')
except FileNotFoundError:
    print("data.csv not found; using a fallback DataFrame.")
    df = pd.DataFrame({
        "Name": ["A", "B", "C"],
        "total points": [80, 90, 70]
    })

data.csv not found; using a fallback DataFrame.

In [39]:
#pd.concat():It combines two or more DataFrames vertically or horizontally.
df1 = pd.DataFrame({
    'Name': ['sai', 'chinna']
})

df2 = pd.DataFrame({
    'Name': ['jaya', 'Anu']
})

print(pd.concat([df1, df2], ignore_index=True))

     Name
0     sai
1  chinna
2    jaya
3     Anu

In [40]:
#df.sort_index(): It arranges rows according to their index values.
df = pd.DataFrame({
    'Marks': [80, 90, 70]
}, index=[2, 0, 1])

print(df.sort_index())

   Marks
0     90
1     70
2     80

In [41]:
#df.join():It joins two DataFrames using their index.
df1 = pd.DataFrame({
    'Name': ['anu', 'Sai']
}, index=[1, 2])

df2 = pd.DataFrame({
    'Marks': [80, 90]
}, index=[1, 2])

print(df1.join(df2))

  Name  Marks
1  anu     80
2  Sai     90

In [42]:
#pd.merge():It combines dataframes using a common column.
df1 = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['anu', 'Sai']
})

df2 = pd.DataFrame({
    'ID': [1, 2],
    'Marks': [809, 920]
})

print(pd.merge(df1, df2, on='ID'))

   ID Name  Marks
0   1  anu    809
1   2  Sai    920

In [43]:
#df.all(): It checks whether every value is True.
print(df.all())

Marks    True
dtype: bool

In [44]:
#df.copy():It creates an separate dataframe so changes don't directly affect the original.
df = pd.DataFrame({
    'Marks': [80, 90]
})

new_df = df.copy()

print(new_df)

   Marks
0     80
1     90

In [45]:
#df.shift():It moves data by a specified number of rows.
df = pd.DataFrame({
    'Marks': [622, 860, 790]
})

print(df['Marks'].shift(1))

0      NaN
1    622.0
2    860.0
Name: Marks, dtype: float64

In [46]:
#df.any():It checks whether at least one value is True in a row or column.
df = pd.DataFrame({
    'A': [True, False, False],
    'B': [False, False, True]
})

print(df.any())

A    True
B    True
dtype: bool

In [47]:
#df.all(): It checks whether every value is True.
print(df.all())

A    False
B    False
dtype: bool

In [48]:
#df.empty:It returns True when the dataframe has no data.
df = pd.DataFrame()

print(df.empty)

True